name: LoginTools
main: regalowl.logintools.LoginTools
version: 0.1
author: RegalOwl
depend: [DataBukkit]
commands:
   playerip:
      description: This command gets.
      permission: loginlist.getip
      permission-message: Unknown command. Type "help" for help.
      aliases: [pip]
   playertime:
      description: This command displays information about the specified player.
      permission: loginlist.pt
      permission-message: Unknown command. Type "help" for help.
      aliases: [pt]
   lstats:
      description: Displays logintools statistics.
      permission: logintools.admin
      permission-message: Unknown command. Type "help" for help.
      aliases: [lst]
   sharedip:
      description: Displays players that have used the same IP as the specified one.
      permission: logintools.admin
      permission-message: Unknown command. Type "help" for help.
      aliases: [sip]
   toptime:
      description: Displays players with the top server playtimes.
      permission: logintools.top
      permission-message: Unknown command. Type "help" for help.
      aliases: [tot]
   topkills:
      description: Displays players with the top server kills.
      permission: logintools.top
      permission-message: Unknown command. Type "help" for help.
      aliases: [tok]
   topdeaths:
      description: Displays players with the top server deaths.
      permission: logintools.top
      permission-message: Unknown command. Type "help" for help.
      aliases: [tod]
permissions:
    logintools.admin:
        description: Gives access to all commands
        default: op
        children:
            loginlist.pt: true
            loginlist.getip: true
            logintools.top: true
    logintools.pt:
        description: Allows display of player time.
        default: false
    logintools.getip:
        description: Gets all of the selected player's ip addresses.
        default: false
    logintools.top:
        description: Allows access to top commands.
        default: false